# Assignment 4-Bank dataset

In [9]:
import numpy as np
import pandas as pd


In [10]:
from google.colab import files
uploaded = files.upload()

Saving bank.csv to bank (2).csv


In [12]:
dataset = pd.read_csv("bank.csv")

In [13]:
dataset.head()

age         job  marital  education  ... pdays  previous poutcome deposit
0   59      admin.  married  secondary  ...    -1         0  unknown     yes
1   56      admin.  married  secondary  ...    -1         0  unknown     yes
2   41  technician  married  secondary  ...    -1         0  unknown     yes
3   55    services  married  secondary  ...    -1         0  unknown     yes
4   54      admin.  married   tertiary  ...    -1         0  unknown     yes

[5 rows x 17 columns]

In [14]:
dataset.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [16]:
dataset.head()

age         job  marital  education  ... pdays  previous poutcome deposit
0   59      admin.  married  secondary  ...    -1         0  unknown     yes
1   56      admin.  married  secondary  ...    -1         0  unknown     yes
2   41  technician  married  secondary  ...    -1         0  unknown     yes
3   55    services  married  secondary  ...    -1         0  unknown     yes
4   54      admin.  married   tertiary  ...    -1         0  unknown     yes

[5 rows x 17 columns]

In [17]:
dataset.shape

(11162, 17)

In [18]:
x=dataset.iloc[:,0:16].values
y=dataset.iloc[:,16].values

In [19]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [20]:
y

array(['yes', 'yes', 'yes', ..., 'no', 'no', 'no'], dtype=object)

In [21]:
x.shape

(11162, 16)

In [22]:
y.shape

(11162,)

In [23]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh", OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder="passthrough")
x=ct.fit_transform(x)

In [24]:
x.shape

(11162, 51)

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [26]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=50)

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [29]:
x_test

array([[-0.37786775, -0.45715156, -0.17451892, ..., -0.55580063,
        -0.49426964, -0.32754405],
       [-0.37786775,  2.18745836, -0.17451892, ..., -0.19364633,
        -0.49426964, -0.32754405],
       [ 2.64642858, -0.45715156, -0.17451892, ..., -0.55580063,
        -0.49426964, -0.32754405],
       ...,
       [-0.37786775,  2.18745836, -0.17451892, ..., -0.19364633,
        -0.49426964, -0.32754405],
       [-0.37786775, -0.45715156, -0.17451892, ...,  0.16850798,
        -0.49426964, -0.32754405],
       [-0.37786775, -0.45715156, -0.17451892, ...,  1.25497091,
        -0.49426964, -0.32754405]])

In [30]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
ypred=logreg.predict(x_test)

In [32]:
ypred

array([1, 0, 0, ..., 0, 0, 0])

In [33]:
y_test

array([1, 0, 1, ..., 0, 0, 0])

In [34]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(ypred,y_test)
accuracy

0.825347066726377

In [35]:
dataset.head()

age         job  marital  education  ... pdays  previous poutcome deposit
0   59      admin.  married  secondary  ...    -1         0  unknown     yes
1   56      admin.  married  secondary  ...    -1         0  unknown     yes
2   41  technician  married  secondary  ...    -1         0  unknown     yes
3   55    services  married  secondary  ...    -1         0  unknown     yes
4   54      admin.  married   tertiary  ...    -1         0  unknown     yes

[5 rows x 17 columns]

In [36]:

logreg.predict(sc.transform(ct.transform([[55,"services","married","secondary","no",2476,"yes","no","unknown",5,"may",579,1,-1,0,"unknown"]])))

array([0])